In [13]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,mean_squared_error
from sklearn.preprocessing import PolynomialFeatures
from matplotlib import pyplot as plt


In [15]:
df=pd.read_csv('dataset.csv')

In [17]:
df.head()

f1        f2        f3        f4        f5        f6        f7  \
0 -0.924357 -0.326536 -1.875007 -1.780626 -0.630143  0.788204  2.792209   
1  0.001795 -1.285599 -0.726774  0.385711  0.891863  0.599451 -0.140553   
2  0.956702  2.319330 -0.705012  0.081829  0.330880  0.838491  2.493000   
3 -0.982294  0.190424  1.082691  0.714610 -1.907808  0.224216  0.156973   
4 -0.057061 -0.592465 -2.850030 -1.935430  2.002427 -1.012644  1.059950   

         f8        f9       f10  ...      f142      f143      f144      f145  \
0 -0.772192 -0.450994  0.400000  ...  0.968645 -0.702053 -0.327662 -0.392108   
1 -0.761760  0.117707  0.333231  ...  0.856399  0.214094 -1.245739  0.173181   
2  1.227669 -0.785989 -0.920674  ... -0.493001 -0.589365  0.849602  0.357015   
3  0.556553  0.058984 -1.397118  ...  0.491919 -1.320233  1.831459  1.179440   
4 -1.000629  0.141596 -0.642776  ...  1.479944  0.077368 -0.861284  1.523124   

       f146      f147      f148      f149      f150      target  
0 -1.463515  0.296120  0.261055  0.005113 -0.234587   10.681366  
1  0.385317 -0.883857  0.153725  0.058209 -1.142970  -60.163343  
2 -0.692910  0.899600  0.307300  0.812862  0.629629  131.226545  
3 -0.469176 -1.713135  1.353872 -0.114540  1.237816 -131.889020  
4  0.538910 -1.037246 -0.190339 -0.875618 -1.382800 -138.566956  

[5 rows x 151 columns]

In [20]:
X=df.drop(['target'],axis=1)

In [22]:
X

f1        f2        f3        f4        f5        f6        f7  \
0   -0.924357 -0.326536 -1.875007 -1.780626 -0.630143  0.788204  2.792209   
1    0.001795 -1.285599 -0.726774  0.385711  0.891863  0.599451 -0.140553   
2    0.956702  2.319330 -0.705012  0.081829  0.330880  0.838491  2.493000   
3   -0.982294  0.190424  1.082691  0.714610 -1.907808  0.224216  0.156973   
4   -0.057061 -0.592465 -2.850030 -1.935430  2.002427 -1.012644  1.059950   
..        ...       ...       ...       ...       ...       ...       ...   
195  1.146487 -0.339530 -2.508957  0.252195 -0.384182  0.184859 -0.770425   
196 -0.357029 -1.091701  0.534506 -2.153343  1.051948 -0.526035  0.420973   
197  0.099314  0.023081 -2.367478  0.309727 -0.220018 -1.680870  0.395599   
198 -0.051119  0.030476 -0.111319  0.520689  0.257253  0.466431 -0.702911   
199 -0.592464 -0.562168  0.288694 -0.088363 -0.646227 -0.109610  0.006422   

           f8        f9       f10  ...      f141      f142      f143  \
0   -0.772192 -0.450994  0.400000  ...  0.097078  0.968645 -0.702053   
1   -0.761760  0.117707  0.333231  ... -0.446515  0.856399  0.214094   
2    1.227669 -0.785989 -0.920674  ... -0.208122 -0.493001 -0.589365   
3    0.556553  0.058984 -1.397118  ... -0.898415  0.491919 -1.320233   
4   -1.000629  0.141596 -0.642776  ... -0.007973  1.479944  0.077368   
..        ...       ...       ...  ...       ...       ...       ...   
195  0.613266 -1.112327 -0.166815  ...  0.047515 -0.960417  1.565103   
196  1.995667  0.890383  0.497743  ...  0.457401  0.138976  0.417681   
197  0.633225 -0.390409 -0.948749  ...  0.893473 -0.519942  1.021659   
198 -0.545087  0.016125 -2.707544  ...  0.727490 -2.205935 -0.733608   
199  1.000582 -0.026406 -1.748532  ...  1.232867 -0.468661  0.888839   

         f144      f145      f146      f147      f148      f149      f150  
0   -0.327662 -0.392108 -1.463515  0.296120  0.261055  0.005113 -0.234587  
1   -1.245739  0.173181  0.385317 -0.883857  0.153725  0.058209 -1.142970  
2    0.849602  0.357015 -0.692910  0.899600  0.307300  0.812862  0.629629  
3    1.831459  1.179440 -0.469176 -1.713135  1.353872 -0.114540  1.237816  
4   -0.861284  1.523124  0.538910 -1.037246 -0.190339 -0.875618 -1.382800  
..        ...       ...       ...       ...       ...       ...       ...  
195  0.500333 -0.774601 -0.993825  0.307204  0.044206  0.832110  0.546968  
196  0.093365 -0.659427  0.004001 -0.714387 -0.780377 -0.336150 -0.119423  
197  0.059655 -0.163061  0.756115 -0.531876 -0.286706  0.670167 -0.031396  
198 -0.725518  1.187127 -1.113844  0.226657 -0.128128  1.043043  0.595832  
199  0.902492  0.952591  0.387827  1.377367  0.378354  1.713530 -1.619920  

[200 rows x 150 columns]

In [24]:
y=df['target']

In [26]:
y

0       10.681366
1      -60.163343
2      131.226545
3     -131.889020
4     -138.566956
          ...    
195    -18.681830
196    234.589644
197    -94.329646
198     80.152034
199    110.131842
Name: target, Length: 200, dtype: float64

In [30]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)

In [28]:
Linear_model=LinearRegression()

In [32]:
Linear_model.fit(X_train,y_train)

LinearRegression()

In [36]:
Linear_model.score(X_test,y_test)

0.7382357071523057

In [38]:
Lasso_model=Lasso(alpha=1.0)

In [40]:
Lasso_model.fit(X_train,y_train)

Lasso()

In [42]:
Lasso_model.score(X_test,y_test)

0.9901476660336154

In [46]:
Ridge_model=Ridge(alpha=1.0)

In [48]:
Ridge_model.fit(X_test,y_test)

Ridge()

In [50]:
Ridge_model.score(X_test,y_test)

0.9999139143135097

In [52]:
Ridge_model.predict(X_test)

array([  40.11102191,  209.14502378,  108.12963495,  196.73356415,
        -86.40582225,  142.33583069,  -50.27414503, -108.7862073 ,
       -130.29343793, -174.38697398,  174.34184473,   73.33661912,
       -107.16919084,  -94.09596505,   23.63496498,  -51.05987161,
       -129.71977458,  141.47390394,  149.72869639,  -67.94643483,
        137.45980537,   55.98535129,  -66.02811081,   29.65138038,
        -61.56564378, -106.73239607,  -56.91855511,    3.82519162,
        207.65854699,  -75.47533119, -114.88143981, -174.01492373,
        -20.09796023,   11.87218226,   71.63252621,   30.46403442,
        111.37550192,  -10.17943597,  -47.85568422,   30.92850994,
        -16.37419765,  -93.06653894,   13.68301198,  130.19256871,
       -348.14828798,  -18.60572487,  301.01509334,  129.73280604,
       -176.97938978,  238.75925892])

95      40.722471
15     210.064672
30     108.833073
158    198.377185
128    -87.044822
115    144.430205
69     -52.043950
170   -110.561339
174   -130.341046
45    -176.307227
66     175.257112
182     73.505074
165   -107.835435
78     -94.554655
186     22.491120
177    -51.725656
56    -130.600523
152    142.534602
82     151.287423
68     -69.573950
124    140.041044
16      55.697495
148    -66.076529
93      28.400494
65     -62.436108
60    -107.000652
84     -56.373950
67       4.133193
125    208.445573
132    -76.681839
9     -115.479545
18    -175.516244
55     -20.193763
75      12.701868
150     73.486489
104     32.380157
135    113.090516
137    -11.377882
164    -47.702714
76      31.663733
79     -17.334274
197    -94.329646
38      13.336016
24     130.354943
122   -350.535447
195    -18.681830
29     301.973805
19     130.524825
143   -177.908598
86     240.629966
Name: target, dtype: float64

In [60]:
Linear_model.coef_[:4],Linear_model.intercept_

(array([ 30.57745869, -35.77372452,  13.35279782,   0.12629716]),
 -2.891323758684271)

In [62]:
Lasso_model.coef_[:4],Lasso_model.intercept_

(array([-0.        , -0.24441233, 19.72524353,  0.        ]),
 0.40750894954108396)