from sklearn.linear_model import LinearRegression
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt 
import seaborn as sns

In [5]:
df=pd.read_csv('home_prices.csv')

In [7]:
df.head()

area_sqr_ft  price_lakhs
0          656         39.0
1         1260         83.2
2         1057         86.6
3         1259         59.0
4         1800        140.0

In [9]:
df.shape

(12, 2)

In [17]:
model=LinearRegression()

In [19]:
X=df[['area_sqr_ft']]
y=df['price_lakhs']

In [21]:
model.fit(X,y)

LinearRegression()

In [23]:
model.predict([[1200],[1600]])

C:\Users\mahim\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([ 80.06460769, 100.73730989])

Internal mechanism

In [26]:
model.coef_,model.intercept_


(array([0.05168176]), 18.046501102723433)

y=mx+b where b=intercept , m=slope(coef_) y=price(target)  x = independent variable (Area)

In [31]:
price=model.coef_*1200+model.intercept_

In [33]:
price_1=model.coef_*1600+model.intercept_

In [35]:
price,price_1

(array([80.06460769]), array([100.73730989]))

### Multiple linear regression

In [38]:
df1=pd.read_csv('home_price.csv')

In [40]:
df1.head()

area_sqr_ft  price_lakhs  bedrooms
0          656         39.0         2
1         1260         83.2         2
2         1057         86.6         3
3         1259         59.0         2
4         1800        140.0         3

In [48]:
X1=df1[['area_sqr_ft','bedrooms']]
y1=df1['price_lakhs']

In [50]:
X1

area_sqr_ft  bedrooms
0           656         2
1          1260         2
2          1057         3
3          1259         2
4          1800         3
5          1325         2
6          1085         3
7          1110         2
8          1700         3
9           960         2
10         1800         3
11          700         2

In [52]:
model.fit(X1,y1)

LinearRegression()

In [62]:
test=pd.DataFrame([{'area_sqr_ft': 1500,'bedrooms': 2},
                  { 'area_sqr_ft': 1200,'bedrooms': 3}
    
])

In [64]:
test

area_sqr_ft  bedrooms
0         1500         2
1         1200         3

In [66]:
model.predict(test)

array([75.78971293, 98.82088159])

In [71]:
model.score(X1,y1)

0.6261935689112181

Internal mechanism

y=m1*Area+m2*Bedrooms+B

In [75]:
model.coef_,model.intercept_

(array([2.66959723e-02, 3.10399604e+01]), -26.334166207939006)

In [79]:
price=model.coef_[0]*1500+model.coef_[1]*2+model.intercept_
price1=model.coef_[0]*1200+model.coef_[1]*3+model.intercept_

In [83]:
price,price_1

(75.78971292846884, array([100.73730989]))