In [7]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,mean_squared_error

In [9]:
df=pd.read_csv('home_price_1.csv')

In [11]:
df.shape

(22, 4)

In [94]:
df

locality  area_sqr_ft  price_lakhs  bedrooms
0          Kollur          656         39.0         2
1          Kollur         1260         83.2         2
2          Kollur         1057         86.6         3
3          Kollur         1259         59.0         2
4          Kollur         1800        140.0         3
5          Kollur         1325         80.1         2
6          Kollur         1085        116.0         3
7          Kollur         1110         45.0         2
8          Kollur         1700        100.0         3
9   Banjara Hills         1650        200.0         3
10  Banjara Hills         2438        316.0         3
11  Banjara Hills         2115        220.0         2
12  Banjara Hills         1600        150.0         3
13  Banjara Hills         2400        300.0         3
14  Banjara Hills         1100         85.0         2
15  Banjara Hills         2600        400.0         3
16        Mankhal         1100         54.0         2
17        Mankhal         1125         64.0         2
18        Mankhal         1008         50.0         2
19        Mankhal         1266         78.0         2
20        Mankhal         1540         94.0         3
21        Mankhal         1200         85.0         3

In [15]:
df_encoded=pd.get_dummies(df,columns=['locality'],drop_first=True)

In [21]:
df_encoded.sample(5)

area_sqr_ft  price_lakhs  bedrooms  locality_Kollur  locality_Mankhal
21         1200         85.0         3            False              True
0           656         39.0         2             True             False
8          1700        100.0         3             True             False
14         1100         85.0         2            False             False
16         1100         54.0         2            False              True

In [25]:
df['locality'].unique()

array(['Kollur', 'Banjara Hills', 'Mankhal'], dtype=object)

In [31]:
X=df_encoded.drop(['price_lakhs'],axis=1)

In [33]:
X

area_sqr_ft  bedrooms  locality_Kollur  locality_Mankhal
0           656         2             True             False
1          1260         2             True             False
2          1057         3             True             False
3          1259         2             True             False
4          1800         3             True             False
5          1325         2             True             False
6          1085         3             True             False
7          1110         2             True             False
8          1700         3             True             False
9          1650         3            False             False
10         2438         3            False             False
11         2115         2            False             False
12         1600         3            False             False
13         2400         3            False             False
14         1100         2            False             False
15         2600         3            False             False
16         1100         2            False              True
17         1125         2            False              True
18         1008         2            False              True
19         1266         2            False              True
20         1540         3            False              True
21         1200         3            False              True

In [35]:
y=df_encoded['price_lakhs']

In [37]:
y

0      39.0
1      83.2
2      86.6
3      59.0
4     140.0
5      80.1
6     116.0
7      45.0
8     100.0
9     200.0
10    316.0
11    220.0
12    150.0
13    300.0
14     85.0
15    400.0
16     54.0
17     64.0
18     50.0
19     78.0
20     94.0
21     85.0
Name: price_lakhs, dtype: float64

In [39]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [46]:
X_train.shape

(15, 4)

In [52]:
model=LinearRegression()


In [54]:
model.fit(X_train,y_train)

LinearRegression()

In [68]:
model.predict(X_test)

array([ -7.00319821, 285.56357359, 157.78129843,  69.16956721,
       310.7863436 ,  77.36696746, 143.16807255])

In [70]:
y_test

0      39.0
13    300.0
8     100.0
1      83.2
15    400.0
5      80.1
20     94.0
Name: price_lakhs, dtype: float64

In [72]:
model.score(X_test,y_test)

0.8549604887953335

In [80]:
Ridge_model=Ridge(alpha=0.5)

In [82]:
Ridge_model.fit(X_train,y_train)

Ridge(alpha=0.5)

In [84]:
Ridge_model.predict(X_test)

array([ -8.16691974, 285.69724623, 163.31175019,  74.77110233,
       313.16016744,  83.69655172, 145.82886437])

In [88]:
Ridge_model.score(X_test,y_test)

0.8504537298172427

In [90]:
test=pd.DataFrame([{'area_sqr_ft':1400,'bedrooms':3,'locality_Kollur':True,'locality_Mankhal':False},
                   {'area_sqr_ft':1400,'bedrooms':3,'locality_Kollur':False,'locality_Mankhal':True},
                   {'area_sqr_ft':1400,'bedrooms':3,'locality_Kollur':False,'locality_Mankhal':False},
 
    
])

In [92]:
model.predict(test)

array([119.94714342, 125.51213354, 159.44972356])